defaults:
  - vehicle: default
  - envs: default 
  - planner: pure_pursuit

num_episodes: ???
num_steps: 10000

output_dir: ./datasets/ ## output h5 file

render: True
render_mode: human ## human or human_fast
hydra:
  run:
    dir: ./outputs/collect_data/${now:%Y-%m-%d}/${now:%H-%M-%S}